#!/usr/bin/env bash
# inspired from https://github.com/diffplug/spotless/issues/178#issuecomment-351638034

echo "==> Running the pre-commit git hook..."

# stash any unstaged changes
git stash --keep-index --include-untracked | grep -vi "No local changes to save"
STASHED=$?

# run all checks before committing
./gradlew check
RESULT=$?

# unstash any stashed changes
if [ "$STASHED" -eq 0 ]; then
  git stash pop -q
fi

if [ "$RESULT" -ne 0 ]; then
  echo
  echo "If you are seeing spotless failures, run:"
  echo "./gradlew spotlessApply"
  echo
fi

# return Gradle's exit code
exit $RESULT
