#!/usr/bin/env bash
# inspired from https://github.com/diffplug/spotless/issues/178#issuecomment-351638034

echo "==> Running the pre-push git hook..."

# stash any unstaged changes
git stash -q --keep-index --include-untracked

# run tests with the gradle wrapper
./gradlew check test --daemon

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew test' exit code
exit $RESULT
