#!/usr/bin/env bash
# inspired from https://github.com/diffplug/spotless/issues/178#issuecomment-351638034

echo "==> Running the pre-commit git hook..."

# stash any unstaged changes
git stash -q --keep-index --include-untracked

# run the spotlessCheck with the gradle wrapper
./gradlew spotlessCheck --daemon

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew spotlessCheck' exit code
exit $RESULT

./gradlew check test
